feat: add balance multi endpoint, docs and tests
railmap/etherscan pull request #11
Opened 2024-02-22 13:33 UTC by EN2U

2024-02-22 20:29 UTC, oxcabe requested changes
I'll change this PR to be a draft. Remember to either remove or use commented code and console logs.

Also, looking good so far!

2024-02-26 14:41 UTC, oxcabe commented on src/account/balance_multi/call.ts
> +// import * as Either from "effect/Either";
don't leave uncommented code!

2024-02-26 16:01 UTC, EN2U commented on src/account/balance_multi/index.ts
fixed

2024-02-26 16:10 UTC, EN2U commented on src/constants.ts
> +export const InvalidAddress = "Invalid";
Done

2024-02-26 17:49 UTC, EN2U commented on src/account/balance_multi/call.ts
> +    });
I have a problem in this line:
`Type 'bigint | undefined' is not assignable to type '[]'.
  Type 'undefined' is not assignable to type '[]'.`
  
The problem are the following types:

```
export interface balanceMultiResultFields {
  address: string;
  balance: bigint;
}

/**
 * Response from the `account/balancemulti` action.
 */
export type BalanceMultiResult = EtherscanResult<balanceMultiResultFields[]>;

export interface EtherscanResult<T> {
  result?: T extends EtherscanResultObjectItem
    ? EtherscanResultObject<T>
    : EtherscanResultPrimitive;

  error?: EtherscanError;
}

```

the thing is, if i change `balanceMultiResultFields` by `EtherscanResultObjectItem` it gets fixed, but the typing now is not detected as an array and the `baseResultList.forEach` simply explodes and throw you an error because is not an array type. I dont know what to do to be honest, i tried some tricky extends features to make it work but it didnt work as i expected

2024-02-26 17:55 UTC, EN2U commented on src/types/param.ts
> +export interface AddressMultiParam extends EtherscanParam {
Done

2024-02-26 17:56 UTC, EN2U commented on src/types/param.ts
>  export class InvalidAddressFormatError extends ParamError.extend(
repeated comment

2024-02-26 23:57 UTC, oxcabe requested changes

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance/call.ts
> +import { InvalidAddress } from "etherscan/fixtures";
I'm not convinced about having this `InvalidAddress` const stuff the way it is right now but, in any case, since it's only used for testing purposes, the import statement has to go [inside the testing block](https://github.com/railmap/etherscan/pull/11/files#diff-b6b3459be3358d2c931581cab3ea0ef66b2a19445d0918560afdd4475ba76a2fR46).

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance/call.ts
>        const { result } = await balance(EtherscanBaseUrl.Sepolia, balanceParams);
I understand your intention here but, to be fair, I don't really see any other advantage for this refactor than just removing a line of code for some tests. On the other side, it comes with some disadvantages:
* Importing and using `beforeAll` adds overhead.
* The test cases that benefit from it are slightly less legible because of the arranging / acting contexts moved elsewhere.
* The test case that does not benefit from it executes it as well, causing significant overhead (since it's an API call to a remote service) and it's also uncool to abuse calling the API like this, negatively affecting API rate limits.

2024-02-26 23:57 UTC, oxcabe commented on src/types/param.ts
> +  apiKey?: string | undefined;
I want to know the motivations for this addition, because I believe (not completely sure) this is unnecessary.

2024-02-26 23:57 UTC, oxcabe commented on src/fixtures.ts
> +
Document

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/index.ts
> +export * from "./types";
Add `./constants` too for this action and the `balance` one respectively.

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/constants.ts
> +
Don't leave newlines between documentation comments and definitions.

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/call.ts
> +    // TODO: we should create a default error tests suit. This tests is repeated on
I would agree with this but, since I don't know the code behind each endpoint, I would not risk it. Also, don't leave `TODO:` comments when merging, just open an issue when it's appropiate and delete the comment afterwards.

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/call.ts
> +    it("should return an object with a balance greater or equal than zero", async () => {
I think you forgot to set a proper test name after copying the previous one.

2024-02-26 23:57 UTC, oxcabe commented on src/fixtures.ts
> +    address: process.env.SEPOLIA_ADDRESS ?? "",
Not all actions have `address` as a param, this is an error prone generalization.

2024-02-26 23:57 UTC, oxcabe commented on src/account/index.ts
> +export * from "./balance_multi";
Out of curiosity, why is this module named using snake case, instead of using the literal action name, `balancemulti`?

2024-02-26 23:57 UTC, oxcabe commented on src/types/param.ts
> +export interface AddressesParam extends EtherscanParam {
This needs further, more informal discussion.

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance/fixtures.ts
> +    ...baseParamsFixture(),
Placing this one first could be more semantic.

2024-02-26 23:57 UTC, oxcabe commented on src/types/param.ts
> +export type DefaultParams = EtherscanParams<AddressParam>;
The naming of this type is confusing and doesn't represent neither its documentation nor its definition.

2024-02-26 23:57 UTC, oxcabe commented on src/fixtures.ts
> +import { type DefaultParams } from "./types/param";
Pedantic but do this instead:

```
import type { DefaultParams } from "./types/param";
```

2024-02-26 23:57 UTC, oxcabe commented on src/account/index.ts
> +import type { BalanceMultiAction } from "./balance_multi/types";
```
import type { BalanceMultiAction } from "etherscan/account/balance_multi";
```

2024-02-26 23:57 UTC, oxcabe commented on src/account/fixtures.ts
Empty?

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/types.ts
> +
Remove any newline between definitions and documentation comments.

2024-02-26 23:57 UTC, oxcabe commented on src/account/balance_multi/fixtures.ts
> +import { TagValue } from "etherscan/types/param";
Add a line here.

2024-02-26 23:58 UTC, oxcabe commented on src/account/balance_multi/call.ts
> +    });
I'm aware of this conversation, will address it tomorrow!

2024-02-27 00:07 UTC, oxcabe commented on src/types/param.ts
> +  apiKey?: string | undefined;
See "optional vs undefined".

2024-02-27 09:27 UTC, EN2U commented on src/account/balance_multi/index.ts
> +export * from "./types";
done

2024-02-27 09:28 UTC, EN2U commented on src/account/index.ts
> +export * from "./balance_multi";
Done

2024-02-27 09:30 UTC, EN2U commented on src/fixtures.ts
> +import { type DefaultParams } from "./types/param";
done

2024-02-27 09:31 UTC, EN2U commented on src/account/index.ts
> +import type { BalanceMultiAction } from "./balance_multi/types";
Done

2024-02-27 09:33 UTC, EN2U commented on src/account/fixtures.ts
Done

2024-02-27 09:33 UTC, EN2U commented on src/account/balance_multi/fixtures.ts
> +import { TagValue } from "etherscan/types/param";
Done

2024-02-27 09:33 UTC, EN2U commented on src/account/balance_multi/types.ts
> +
Done

2024-02-27 09:36 UTC, EN2U commented on src/account/balance_multi/call.ts
> +    it("should return an object with a balance greater or equal than zero", async () => {
Done

2024-02-27 09:37 UTC, EN2U commented on src/account/balance_multi/call.ts
> +    // TODO: we should create a default error tests suit. This tests is repeated on
i just added to discuss it with you. I understund your comment. Ill simply remove it

2024-02-27 09:38 UTC, EN2U commented on src/account/balance_multi/constants.ts
> +
Done

2024-02-27 10:14 UTC, EN2U commented on src/types/param.ts
> +export type DefaultParams = EtherscanParams<AddressParam>;
Done

2024-02-27 10:41 UTC, EN2U commented on src/fixtures.ts
> +    address: process.env.SEPOLIA_ADDRESS ?? "",
DOne

2024-02-27 10:43 UTC, EN2U commented on src/fixtures.ts
> +
Done

2024-03-01 17:36 UTC, oxcabe approved these changes

2024-03-01 18:36 UTC, oxcabe approved these changes

2024-03-01 18:37 UTC, merged