feat: add first endpoint call, types, tests and docs
railmap/etherscan pull request #3
Opened 2024-02-09 18:08 UTC by oxcabe

This is WIP still. Take a look at it in the meanwhile.

2024-02-12 19:17 UTC, EN2U commented on src/account/index.ts
> +export type AccountModuleRequest = EtherscanModuleRequest<"account">;
I think we should add "account" string as a constant

2024-02-12 19:18 UTC, oxcabe commented on src/account/index.ts
> +export type AccountModuleRequest = EtherscanModuleRequest<"account">;
I agree

2024-02-12 19:22 UTC, oxcabe commented on src/account/index.ts
> +export type AccountModuleRequest = EtherscanModuleRequest<"account">;
Added in [a17c665](https://github.com/railmap/etherscan/pull/3/commits/a17c66532911ff85bc63dd0474bb01a37325c0ff).

2024-02-14 10:16 UTC, EN2U requested changes
Great code! in general i just simply suggest to add the strings as "address" to add them as constants. This ensures that no one gets the syntax or spelling wrong.

For tests, we could also separate the checks into functions. That is to say, the it() section could be extracted in a function so that the tests do not scale and are easier to read.

2024-02-14 11:44 UTC, oxcabe commented on src/account/balance/call.ts
> +    };
I agree

2024-02-14 12:00 UTC, oxcabe commented on src/account/balance/call.ts
> +}
Yes, it's just not necessary for the current state of the project. It is fair to have this in mind for the future, though.

2024-02-19 13:25 UTC, EN2U approved these changes
Everything is OK!

We have to talk about the decorator usage for handling errors but we can solve it in another pr

2024-02-19 13:25 UTC, EN2U commented on src/errors.ts
> +}
we should discuss this about using a [decorator](https://stackoverflow.com/a/46187742)

2024-02-19 13:30 UTC, merged